# Generated by Django 3.0.4 on 2020-04-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200403_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='teamName',
        ),
    ]
