# Generated by Django 3.0.4 on 2020-04-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200410_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamName',
            new_name='team_name',
        ),
    ]
