# Generated by Django 3.0.4 on 2020-03-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20200323_1658'),
        ('profiles', '0002_auto_20200323_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sports',
            field=models.ManyToManyField(blank=True, through='profiles.UserPlaysSport', to='sports.Sport'),
        ),
        migrations.AlterField(
            model_name='userratesusersport',
            name='rated_user_sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserPlaysSport'),
        ),
    ]
