# Generated by Django 3.0.4 on 2020-07-14 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratessport',
            name='rated_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rates_sport_rated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
