# Generated by Django 3.0.8 on 2020-07-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userratessport_rater'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appleId',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fbId',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
