# Generated by Django 3.0.4 on 2020-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200714_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
