# Generated by Django 3.0.8 on 2020-07-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200731_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='appleId',
            new_name='apple_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fbId',
            new_name='fb_id',
        ),
    ]
