# Generated by Django 3.0.4 on 2020-07-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chatmatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMatch',
        ),
    ]
