# Generated by Django 3.0.4 on 2020-07-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200712_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='captain_cnic',
        ),
    ]
