# Generated by Django 3.0.4 on 2020-04-03 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200403_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
